var categories = [
Food (food)
Bagels (bagels)
Bakeries (bakeries)
Beer, Wine & Spirits (beer_and_wine)
Breweries (breweries)
Bubble Tea (bubbletea)
Butcher (butcher)
CSA (csa)
Coffee & Tea (coffee)
Convenience Stores (convenience)
Cupcakes (cupcakes)
Desserts (desserts)
Distilleries (distilleries)
Do-It-Yourself Food (diyfood)
Donuts (donuts)
Farmers Market (farmersmarket)
Food Delivery Services (fooddeliveryservices)
Food Trucks (foodtrucks)
Gelato (gelato)
Grocery (grocery)
Ice Cream & Frozen Yogurt (icecream)
Internet Cafes (internetcafe)
Juice Bars & Smoothies (juicebars)
Pretzels (pretzels)
Shaved Ice (shavedice)
Specialty Food (gourmet)
Candy Stores (candy)
Cheese Shops (cheese)
Chocolatiers & Shops (chocolate)
Ethnic Food (ethnicmarkets)
Fruits & Veggies (markets)
Health Markets (healthmarkets)
Herbs & Spices (herbsandspices)
Meat Shops (meats)
Seafood Markets (seafoodmarkets)
Street Vendors (streetvendors)
Tea Rooms (tea)
Wineries (wineries)
Orthotics (orthotics)
Physical Therapy (physicaltherapy)
Prosthetics (prosthetics)
Reflexology (reflexology)
Rehabilitation Center (rehabilitation_center)
Reiki (reiki)
Retirement Homes (retirement_homes)
Speech Therapists (speech_therapists)
Traditional Chinese Medicine (tcm)
Urgent Care (urgent_care)
Weight Loss Centers (weightlosscenters)
Home Services (homeservices)
Building Supplies (buildingsupplies)
Cabinetry (cabinetry)
Carpet Installation (carpetinstallation)
Carpeting (carpeting)
Chimney Sweeps (chimneysweeps)
Contractors (contractors)
Damage Restoration (damagerestoration)
Door Sales/Installation (doorsales)
Drywall Installation & Repair (drywall)
Electricians (electricians)
Fences & Gates (fencesgates)
Fireplace Services (fireplace)
Firewood (firewood)
Flooring (flooring)
Garage Door Services (garage_door_services)
Gardeners (gardeners)
Glass & Mirrors (glassandmirrors)
Gutter Services (gutterservices)
Handyman (handyman)
Heating & Air Conditioning/HVAC (hvac)
Home Cleaning (homecleaning)
Home Inspectors (home_inspectors)
Home Organization (home_organization)
Home Theatre Installation (hometheatreinstallation)
Home Window Tinting (homewindowtinting)
Insulation Installation (insulationinstallation)
Interior Design (interiordesign)
Internet Service Providers (isps)
Irrigation (irrigation)
Keys & Locksmiths (locksmiths)
Landscape Architects (landscapearchitects)
Landscaping (landscaping)
Lighting Fixtures & Equipment (lighting)
Masonry/Concrete (masonry_concrete)
Movers (movers)
Painters (painters)
Plumbing (plumbing)
Pool & Hot Tub Service (poolservice)
Pool Cleaners (poolcleaners)
Pressure Washers (pressurewashers)
Real Estate (realestate)
Apartments (apartments)
Commercial Real Estate (commercialrealestate)
Home Staging (homestaging)
Mortgage Brokers (mortgagebrokers)
Property Management (propertymgmt)
Real Estate Agents (realestateagents)
Real Estate Services (realestatesvcs)
Shared Office Spaces (sharedofficespaces)
University Housing (university_housing)
Roofing (roofing)
Security Systems (securitysystems)
Shades & Blinds (blinds)
Solar Installation (solarinstallation)
Structural Engineers (structuralengineers)
Television Service Providers (televisionserviceproviders)
Tree Services (treeservices)
Utilities (utilities)
Window Washing (windowwashing)
Windows Installation (windowsinstallation)
Hotels & Travel (hotelstravel)
Airports (airports)
Bed & Breakfast (bedbreakfast)
Campgrounds (campgrounds)
Car Rental (carrental)
Guest Houses (guesthouses)
Health Retreats (healthretreats)
Hostels (hostels)
Hotels (hotels)
Motorcycle Rental (motorcycle_rental)
RV Parks (rvparks)
RV Rental (rvrental)
Resorts (resorts)
Ski Resorts (skiresorts)
Tours (tours)
Train Stations (trainstations)
Transportation (transport)
Airlines (airlines)
Airport Shuttles (airport_shuttles)
Buses (buses)
Limos (limos)
Public Transportation (publictransport)
Taxis (taxis)
Trains (trains)
Travel Services (travelservices)
Vacation Rental Agents (vacationrentalagents)
Vacation Rentals (vacation_rentals)
Local Flavor (localflavor)
Yelp Events (yelpevents)
Local Services (localservices)
Appliances & Repair (homeappliancerepair)
Bail Bondsmen (bailbondsmen)
Bike Repair/Maintenance (bike_repair_maintenance)
Carpet Cleaning (carpet_cleaning)
Child Care & Day Care (childcare)
Community Service/Non-Profit (nonprofit)
Couriers & Delivery Services (couriers)
Dry Cleaning & Laundry (drycleaninglaundry)
Electronics Repair (electronicsrepair)
Funeral Services & Cemeteries (funeralservices)
Furniture Reupholstery (reupholstery)
IT Services & Computer Repair (itservices)
Data Recovery (datarecovery)
Mobile Phone Repair (mobilephonerepair)
Telecommunications (telecommunications)
Jewelry Repair (jewelryrepair)
Junk Removal & Hauling (junkremovalandhauling)
Knife Sharpening (knifesharpening)
Metal Fabricators (metalfabricators)
Nanny Services (nannys)
Notaries (notaries)
Pest Control (pest_control)
Printing Services (copyshops)
Propane (propane)
Recording & Rehearsal Studios (recording_studios)
Recycling Center (recyclingcenter)
Screen Printing (screenprinting)
Screen Printing/T-Shirt Printing (screen_printing_tshirt_printing)
Self Storage (selfstorage)
Septic Services (septicservices)
Sewing & Alterations (sewingalterations)
Shipping Centers (shipping_centers)
Shoe Repair (shoerepair)
Snow Removal (snowremoval)
Watch Repair (watch_repair)
Water Delivery (waterdelivery)
Mass Media (massmedia)
Print Media (printmedia)
Radio Stations (radiostations)
Television Stations (televisionstations)
Nightlife (nightlife)
Adult Entertainment (adultentertainment)
Bars (bars)
Champagne Bars (champagne_bars)
Cocktail Bars (cocktailbars)
Dive Bars (divebars)
Gay Bars (gaybars)
Hookah Bars (hookah_bars)
Irish Pub (irish_pubs)
Lounges (lounges)
Pubs (pubs)
Sports Bars (sportsbars)
Wine Bars (wine_bars)
Comedy Clubs (comedyclubs)
Country Dance Halls (countrydancehalls)
Dance Clubs (danceclubs)
Jazz & Blues (jazzandblues)
Karaoke (karaoke)
Music Venues (musicvenues)
Piano Bars (pianobars)
Pool Halls (poolhalls)
Pets (pets)
Animal Shelters (animalshelters)
Horse Boarding (horse_boarding)
Pet Adoption (petadoption)
Pet Services (petservices)
Aquarium Services (aquariumservices)
Dog Walkers (dogwalkers)
Pet Boarding/Pet Sitting (pet_sitting)
Pet Groomers (groomer)
Pet Training (pet_training)
Pet Stores (petstore)
Veterinarians (vet)
Professional Services (professional)
Accountants (accountants)
Advertising (advertising)
Architects (architects)
Boat Repair (boatrepair)
Career Counseling (careercounseling)
Editorial Services (editorialservices)
Employment Agencies (employmentagencies)
Graphic Design (graphicdesign)
Internet Service Providers (isps)
Lawyers (lawyers)
Bankruptcy Law (bankruptcy)
Business Law (businesslawyers)
Criminal Defense Law (criminaldefense)
DUI Law (duilawyers)
Divorce & Family Law (divorce)
Employment Law (employmentlawyers)
Estate Planning Law (estateplanning)
General Litigation (general_litigation)
IP & Internet Law (iplaw)
Immigration Law (immigrationlawyers)
Personal Injury Law (personal_injury)
Real Estate Law (realestatelawyers)
Tax Law (taxlaw)
Legal Services (legalservices)
Life Coach (lifecoach)
Marketing (marketing)
Matchmakers (matchmakers)
Office Cleaning (officecleaning)
Payroll Services (payroll)
Personal Assistants (personalassistants)
Private Investigation (privateinvestigation)
Public Relations (publicrelations)
Security Services (security)
Shredding Services (shredding)
Signmaking (signmaking)
Software Development (softwaredevelopment)
Talent Agencies (talentagencies)
Taxidermy (taxidermy)
Tenant and Eviction Law (tenantlaw)
Translation Services (translationservices)
Video/Film Production (videofilmproductions)
Web Design (web_design)
Public Services & Government (publicservicesgovt)
Courthouses (courthouses)
Departments of Motor Vehicles (departmentsofmotorvehicles)
Embassy (embassy)
Fire Departments (firedepartments)
Landmarks & Historical Buildings (landmarks)
Libraries (libraries)
Police Departments (policedepartments)
Post Offices (postoffices)
Real Estate (realestate)
Apartments (apartments)
Commercial Real Estate (commercialrealestate)
Home Staging (homestaging)
Mortgage Brokers (mortgagebrokers)
Property Management (propertymgmt)
Real Estate Agents (realestateagents)
Real Estate Services (realestatesvcs)
Shared Office Spaces (sharedofficespaces)
University Housing (university_housing)
Religious Organizations (religiousorgs)
Buddhist Temples (buddhist_temples)
Churches (churches)
Hindu Temples (hindu_temples)
Mosques (mosques)
Synagogues (synagogues)
Restaurants (restaurants)
Afghan (afghani)
African (african)
Senegalese (senegalese)
South African (southafrican)
American (New) (newamerican)
American (Traditional) (tradamerican)
Arabian (arabian)
Argentine (argentine)
Armenian (armenian)
Asian Fusion (asianfusion)
Australian (australian)
Austrian (austrian)
Bangladeshi (bangladeshi)
Barbeque (bbq)
Basque (basque)
Belgian (belgian)
Brasseries (brasseries)
Brazilian (brazilian)
Breakfast & Brunch (breakfast_brunch)
British (british)
Buffets (buffets)
Burgers (burgers)
Burmese (burmese)
Cafes (cafes)
Cafeteria (cafeteria)
Cajun/Creole (cajun)
Cambodian (cambodian)
Caribbean (caribbean)
Dominican (dominican)
Haitian (haitian)
Puerto Rican (puertorican)
Trinidadian (trinidadian)
Catalan (catalan)
Cheesesteaks (cheesesteaks)
Chicken Wings (chicken_wings)
Chinese (chinese)
Cantonese (cantonese)
Dim Sum (dimsum)
Shanghainese (shanghainese)
Szechuan (szechuan)
Comfort Food (comfortfood)
Creperies (creperies)
Cuban (cuban)
Czech (czech)
Delis (delis)
Diners (diners)
Ethiopian (ethiopian)
Fast Food (hotdogs)
Filipino (filipino)
Fish & Chips (fishnchips)
Fondue (fondue)
Food Court (food_court)
Food Stands (foodstands)
French (french)
Gastropubs (gastropubs)
German (german)
Gluten-Free (gluten_free)
Greek (greek)
Halal (halal)
Hawaiian (hawaiian)
Himalayan/Nepalese (himalayan)
Hot Dogs (hotdog)
Hot Pot (hotpot)
Hungarian (hungarian)
Iberian (iberian)
Indian (indpak)
Indonesian (indonesian)
Irish (irish)
Italian (italian)
Japanese (japanese)
Ramen (ramen)
Korean (korean)
Kosher (kosher)
Laotian (laotian)
Latin American (latin)
Colombian (colombian)
Salvadoran (salvadoran)
Venezuelan (venezuelan)
Live/Raw Food (raw_food)
Malaysian (malaysian)
Mediterranean (mediterranean)
Falafel (falafel)
Mexican (mexican)
Middle Eastern (mideastern)
Egyptian (egyptian)
Lebanese (lebanese)
Modern European (modern_european)
Mongolian (mongolian)
Moroccan (moroccan)
Pakistani (pakistani)
Persian/Iranian (persian)
Peruvian (peruvian)
Pizza (pizza)
Polish (polish)
Portuguese (portuguese)
Russian (russian)
Salad (salad)
Sandwiches (sandwiches)
Scandinavian (scandinavian)
Scottish (scottish)
Seafood (seafood)
Singaporean (singaporean)
Slovakian (slovakian)
Soul Food (soulfood)
Soup (soup)
Southern (southern)
Spanish (spanish)
Steakhouses (steak)
Sushi Bars (sushi)
Taiwanese (taiwanese)
Tapas Bars (tapas)
Tapas/Small Plates (tapasmallplates)
Tex-Mex (tex-mex)
Thai (thai)
Turkish (turkish)
Ukrainian (ukrainian)
Uzbek (uzbek)
Vegan (vegan)
Vegetarian (vegetarian)
Vietnamese (vietnamese)
Shopping (shopping)
Adult (adult)
Antiques (antiques)
Art Galleries (galleries)
Arts & Crafts (artsandcrafts)
Art Supplies (artsupplies)
Cards & Stationery (stationery)
Cooking Classes (cookingclasses)
Costumes (costumes)
Embroidery & Crochet (embroideryandcrochet)
Fabric Stores (fabricstores)
Framing (framing)
Auction Houses (auctionhouses)
Baby Gear & Furniture (baby_gear)
Bespoke Clothing (bespoke)
Books, Mags, Music & Video (media)
Bookstores (bookstores)
Comic Books (comicbooks)
Music & DVDs (musicvideo)
Newspapers & Magazines (mags)
Videos & Video Game Rental (videoandgames)
Vinyl Records (vinyl_records)
Brewing Supplies (brewingsupplies)
Bridal (bridal)
Computers (computers)
Cosmetics & Beauty Supply (cosmetics)
Customized Merchandise (custommerchandise)
Department Stores (deptstores)
Discount Store (discountstore)
Drugstores (drugstores)
Electronics (electronics)
Eyewear & Opticians (opticians)
Fashion (fashion)
Accessories (accessories)
Children's Clothing (childcloth)
Department Stores (deptstores)
Formal Wear (formalwear)
Hats (hats)
Leather Goods (leather)
Lingerie (lingerie)
Maternity Wear (maternity)
Men's Clothing (menscloth)
Plus Size Fashion (plus_size_fashion)
Shoe Stores (shoes)
Sports Wear (sportswear)
Surf Shop (surfshop)
Swimwear (swimwear)
Used, Vintage & Consignment (vintage)
Women's Clothing (womenscloth)
Fireworks (fireworks)
Fitness/Exercise Equipment (fitnessequipment)
Flea Markets (fleamarkets)
Flowers & Gifts (flowers)
Cards & Stationery (stationery)
Florists (florists)
Gift Shops (giftshops)
Gold Buyers (goldbuyers)
Golf Equipment Shops (golfshops)
Guns & Ammo (guns_and_ammo)
Hobby Shops (hobbyshops)
Home & Garden (homeandgarden)
Appliances (appliances)
Furniture Stores (furniture)
Hardware Stores (hardware)
Home Decor (homedecor)
Hot Tub & Pool (hottubandpool)
Kitchen & Bath (kitchenandbath)
Mattresses (mattresses)
Nurseries & Gardening (gardening)
Rugs (rugs)
Jewelry (jewelry)
Knitting Supplies (knittingsupplies)
Luggage (luggage)
Medical Supplies (medicalsupplies)
Mobile Phones (mobilephones)
Motorcycle Gear (motorcyclinggear)
Musical Instruments & Teachers (musicalinstrumentsandteachers)
Office Equipment (officeequipment)
Outlet Stores (outlet_stores)
Pawn Shops (pawn)
Personal Shopping (personal_shopping)
Photography Stores & Services (photographystores)
Pool & Billiards (poolbilliards)
Pop-up Shops (popupshops)
Shopping Centers (shoppingcenters)
Sporting Goods (sportgoods)
Bikes (bikes)
Golf Equipment (golfequipment)
Outdoor Gear (outdoorgear)
Sports Wear (sportswear)
Thrift Stores (thrift_stores)
Tobacco Shops (tobaccoshops)
Toy Stores (toys)
Trophy Shops (trophyshops)
Uniforms (uniforms)
Vape Shops (vapeshops)
Watches (watches)
Wholesale Stores (wholesale_stores)
Wigs (wigs)
]
