var categories = [
["Food", "food"[
	["Bagels", "bagels"]
  	["Bakeries", "bakeries"]
  	["Beer, Wine & Spirits", "beer_and_wine"]
  	["Breweries", "breweries"]
  	["Bubble Tea", "bubbletea"]
  	["Butcher", "butcher"]
  	["CSA", "csa"]
  	["Coffee & Tea", "coffee"]
  	["Convenience Stores", "convenience"]
  	["Cupcakes", "cupcakes"]
  	["Desserts", "desserts"]
  	["Distilleries", "distilleries"]
  	["Do-It-Yourself Food", "diyfood"]
  	["Donuts", "donuts"]
  	["Farmers Market", "farmersmarket"]
  	["Food Delivery Services", "fooddeliveryservices"]
  	["Food Trucks", "foodtrucks"]
  	["Gelato", "gelato"]
  	["Grocery", "grocery"]
  	["Ice Cream & Frozen Yogurt", "icecream"]
  	["Internet Cafes", "internetcafe"]
  	["Juice Bars & Smoothies", "juicebars"]
  	["Pretzels", "pretzels"]
  	["Shaved Ice", "shavedice"]
  	["Specialty Food", "gourmet"]
  	["Candy Stores", "candy"]
  	["Cheese Shops", "cheese"]
  	["Chocolatiers & Shops", "chocolate"]
  	["Ethnic Food", "ethnicmarkets"]
  	["Fruits & Veggies", "markets"]
  	["Health Markets", "healthmarkets"]
  	["Herbs & Spices", "herbsandspices"]
  	["Meat Shops", "meats"]
  	["Seafood Markets", "seafoodmarkets"]
  	["Street Vendors", "streetvendors"]
  	["Tea Rooms", "tea"]
  	["Wineries", "wineries"]
	]]
["Bars", "bars"[
	["Champagne Bars", "champagne_bars"]
	["Cocktail Bars", "cocktailbars"]
	["Dive Bars", "divebars"]
	["Gay Bars", "gaybars"]
	["Hookah Bars", "hookah_bars"]
	["Irish Pub", "irish_pubs"]
	["Lounges", "lounges"]
	["Pubs", "pubs"]
	["Sports Bars", "sportsbars"]
	["Wine Bars", "wine_bars"]
	]]
["Restaurants", "restaurants"[
	["Afghan", "afghani"]
	["African", "african"]
	["Senegalese", "senegalese"]
	["South African", "southafrican"]
	["New American", "newamerican"]
	["Traditional American", "tradamerican"]
	["Arabian", "arabian"]
	["Argentine", "argentine"]
	["Armenian", "armenian"]
	["Asian Fusion", "asianfusion"]
	["Australian", "australian"]
	["Austrian", "austrian"]
	["Bangladeshi", "bangladeshi"]
	["Barbeque", "bbq"]
	["Basque", "basque"]
	["Belgian", "belgian"]
	["Brasseries", "brasseries"]
	["Brazilian", "brazilian"]
	["Breakfast & Brunch", "breakfast_brunch"]
	["British", "british"]
	["Buffets", "buffets"]
	["Burgers", "burgers"]
	["Burmese", "burmese"]
	["Cafes", "cafes"]
	["Cafeteria", "cafeteria"]
	["Cajun/Creole", "cajun"]
	["Cambodian", "cambodian"]
	["Caribbean", "caribbean"]
	["Dominican", "dominican"]
	["Haitian", "haitian"]
	["Puerto Rican", "puertorican"]
	["Trinidadian", "trinidadian"]
	["Catalan", "catalan"]
	["Cheesesteaks", "cheesesteaks"]
	["Chicken Wings", "chicken_wings"]
	["Chinese", "chinese"]
	["Cantonese", "cantonese"]
	["Dim Sum", "dimsum"]
	["Shanghainese", "shanghainese"]
	["Szechuan", "szechuan"]
	["Comfort Food", "comfortfood"]
	["Creperies", "creperies"]
	["Cuban", "cuban"]
	["Czech", "czech"]
	["Delis", "delis"]
	["Diners", "diners"]
	["Ethiopian", "ethiopian"]
	["Fast Food", "hotdogs"]
	["Filipino", "filipino"]
	["Fish & Chips", "fishnchips"]
	["Fondue", "fondue"]
	["Food Court", "food_court"]
	["Food Stands", "foodstands"]
	["French", "french"]
	["Gastropubs", "gastropubs"]
	["German", "german"]
	["Gluten-Free", "gluten_free"]
	["Greek", "greek"]
	["Halal", "halal"]
	["Hawaiian", "hawaiian"]
	["Himalayan/Nepalese", "himalayan"]
	["Hot Dogs", "hotdog"]
	["Hot Pot", "hotpot"]
	["Hungarian", "hungarian"]
	["Iberian", "iberian"]
	["Indian", "indpak"]
	["Indonesian", "indonesian"]
	["Irish", "irish"]
	["Italian", "italian"]
	["Japanese", "japanese"]
	["Ramen", "ramen"]
	["Korean", "korean"]
	["Kosher", "kosher"]
	["Laotian", "laotian"]
	["Latin American", "latin"]
	["Colombian", "colombian"]
	["Salvadoran", "salvadoran"]
	["Venezuelan", "venezuelan"]
	["Live/Raw Food", "raw_food"]
	["Malaysian", "malaysian"]
	["Mediterranean", "mediterranean"]
	["Falafel", "falafel"]
	["Mexican", "mexican"]
	["Middle Eastern", "mideastern"]
	["Egyptian", "egyptian"]
	["Lebanese", "lebanese"]
	["Modern European", "modern_european"]
	["Mongolian", "mongolian"]
	["Moroccan", "moroccan"]
	["Pakistani", "pakistani"]
	["Persian/Iranian", "persian"]
	["Peruvian", "peruvian"]
	["Pizza", "pizza"]
	["Polish", "polish"]
	["Portuguese", "portuguese"]
	["Russian", "russian"]
	["Salad", "salad"]
	["Sandwiches", "sandwiches"]
	["Scandinavian", "scandinavian"]
	["Scottish", "scottish"]
	["Seafood", "seafood"]
	["Singaporean", "singaporean"]
	["Slovakian", "slovakian"]
	["Soul Food", "soulfood"]
	["Soup", "soup"]
	["Southern", "southern"]
	["Spanish", "spanish"]
	["Steakhouses", "steak"]
	["Sushi Bars", "sushi"]
	["Taiwanese", "taiwanese"]
	["Tapas Bars", "tapas"]
	["Tapas/Small Plates", "tapasmallplates"]
	["Tex-Mex", "tex-mex"]
	["Thai", "thai"]
	["Turkish", "turkish"]
	["Ukrainian", "ukrainian"]
	["Uzbek", "uzbek"]
	["Vegan", "vegan"]
	["Vegetarian", "vegetarian"]
	["Vietnamese", "vietnamese"]
]]
]